# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build peppakbd"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["peppakbd_left","peppakbd_right","peppakbd_dongle","settings_reset"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
